import 'package:glp_runtime/compiler/compiler.dart';
import 'package:glp_runtime/bytecode/opcodes.dart' as bc;

void main() {
  final compiler = GlpCompiler();
  final source = 'p([X|Xs]).';

  final program = compiler.compile(source);

  print('Generated bytecode for: $source');
  for (var i = 0; i < program.ops.length; i++) {
    print('  $i: ${program.ops[i]}');
  }

  final hasHeadStruct = program.ops.any((op) => op is bc.HeadStructure);
  final hasWriter = program.ops.any((op) => op is bc.UnifyWriter);

  print('\nhasHeadStruct: $hasHeadStruct');
  print('hasWriter: $hasWriter');

  print('\nDetailed type checking:');
  for (var i = 0; i < program.ops.length; i++) {
    final op = program.ops[i];
    print('  $i: ${op.runtimeType} - is UnifyWriter? ${op is bc.UnifyWriter}');
  }
}
